
import { TemplatePreset } from './types';

export const presetTemplates: TemplatePreset[] = [
  {
    id: 'modern-react',
    name: 'Modern React',
    description: 'React with TypeScript and Tailwind CSS',
    framework: 'react',
    features: ['typescript', 'tailwind', 'eslint', 'router'],
    documentation: 'https://react.dev/',
    category: 'core',
    logo: 'react',
  },
  {
    id: 'next-full',
    name: 'Next.js Full Stack',
    description: 'Next.js with TypeScript, Tailwind CSS and API routes',
    framework: 'next',
    features: ['typescript', 'tailwind', 'eslint'],
    documentation: 'https://nextjs.org/docs',
    category: 'core',
    logo: 'next',
  },
  {
    id: 'vue-starter',
    name: 'Vue Starter',
    description: 'Vue 3 with TypeScript and Composition API',
    framework: 'vue',
    features: ['typescript', 'router', 'eslint'],
    documentation: 'https://vuejs.org/guide/',
    category: 'core',
    logo: 'vue',
  },
  {
    id: 'jamstack',
    name: 'JAMstack',
    description: 'Next.js with static generation for high performance',
    framework: 'next',
    features: ['typescript', 'tailwind'],
    documentation: 'https://jamstack.org/',
    category: 'architecture',
    logo: 'next',
  },
  {
    id: 'pwa-ready',
    name: 'PWA Ready',
    description: 'React with service workers for offline capability',
    framework: 'react',
    features: ['typescript', 'tailwind', 'pwa'],
    documentation: 'https://web.dev/progressive-web-apps/',
    category: 'architecture',
    logo: 'react',
  },
  // UI Libraries
  {
    id: 'shadcn-ui',
    name: 'shadcn/ui Setup',
    description: 'Next.js with shadcn/ui component library',
    framework: 'next',
    features: ['typescript', 'tailwind', 'shadcn'],
    documentation: 'https://ui.shadcn.com/',
    category: 'ui',
    logo: 'shadcn',
  },
  {
    id: 'framer-motion',
    name: 'Framer Motion',
    description: 'React with Framer Motion for animations',
    framework: 'react',
    features: ['typescript', 'tailwind', 'framer'],
    documentation: 'https://www.framer.com/motion/',
    category: 'ui',
    logo: 'framer',
  },
  {
    id: 'nextui-setup',
    name: 'NextUI Dashboard',
    description: 'React app with NextUI components',
    framework: 'react',
    features: ['typescript', 'tailwind', 'nextui'],
    documentation: 'https://nextui.org/',
    category: 'ui',
    logo: 'nextui',
  },
  // Payment integrations
  {
    id: 'ecommerce-stripe',
    name: 'E-commerce with Stripe',
    description: 'Next.js setup with Stripe payment processing',
    framework: 'next',
    features: ['typescript', 'tailwind', 'stripe'],
    documentation: 'https://stripe.com/docs',
    category: 'payment',
    logo: 'stripe',
  },
  {
    id: 'razorpay-integration',
    name: 'Razorpay Integration',
    description: 'React app with Razorpay payment gateway',
    framework: 'react',
    features: ['typescript', 'tailwind', 'razorpay'],
    documentation: 'https://razorpay.com/docs/',
    category: 'payment',
    logo: 'razorpay',
  },
  // Cloud provider templates
  {
    id: 'aws-cloud',
    name: 'AWS Cloud Integration',
    description: 'Next.js with AWS SDK for cloud services',
    framework: 'next',
    features: ['typescript', 'tailwind', 'aws'],
    documentation: 'https://aws.amazon.com/documentation/',
    category: 'cloud',
    logo: 'aws',
  },
  {
    id: 'firebase-app',
    name: 'Firebase Full App',
    description: 'React with Firebase Auth and Firestore',
    framework: 'react',
    features: ['typescript', 'tailwind', 'firebase'],
    documentation: 'https://firebase.google.com/docs',
    category: 'cloud',
    logo: 'firebase',
  },
  {
    id: 'supabase-starter',
    name: 'Supabase Starter',
    description: 'Next.js with Supabase authentication and database',
    framework: 'next',
    features: ['typescript', 'tailwind', 'supabase'],
    documentation: 'https://supabase.com/docs',
    category: 'cloud',
    logo: 'supabase',
  },
  // AI templates
  {
    id: 'ai-openai',
    name: 'OpenAI Integration',
    description: 'Next.js with OpenAI API integration',
    framework: 'next',
    features: ['typescript', 'tailwind', 'openai'],
    documentation: 'https://platform.openai.com/docs/',
    category: 'ai',
    logo: 'openai',
  },
  {
    id: 'ai-huggingface',
    name: 'Hugging Face ML',
    description: 'React app with Hugging Face transformers',
    framework: 'react',
    features: ['typescript', 'tailwind', 'huggingface'],
    documentation: 'https://huggingface.co/docs',
    category: 'ai',
    logo: 'huggingface',
  },
  {
    id: 'langchain-app',
    name: 'LangChain AI App',
    description: 'Next.js with LangChain for AI applications',
    framework: 'next',
    features: ['typescript', 'tailwind', 'langchain'],
    documentation: 'https://js.langchain.com/docs/',
    category: 'ai',
    logo: 'langchain',
  },
  // 2025 Trending templates
  {
    id: 'rust-wasm',
    name: 'Rust + WASM',
    description: 'Next.js with Rust compiled to WebAssembly',
    framework: 'next',
    features: ['typescript', 'tailwind'],
    documentation: 'https://rustwasm.github.io/docs/book/',
    category: '2025-trend',
    logo: 'rust',
  },
  {
    id: 'htmx-alpine',
    name: 'HTMX + Alpine.js',
    description: 'Minimal JS approach with HTMX and Alpine',
    framework: 'next',
    features: ['typescript'],
    documentation: 'https://htmx.org/docs/',
    category: '2025-trend',
    logo: 'htmx',
  },
  {
    id: 'qwik-city',
    name: 'Qwik City',
    description: 'Resumable app development with Qwik',
    framework: 'next',
    features: ['typescript', 'tailwind'],
    documentation: 'https://qwik.builder.io/docs/',
    category: '2025-trend',
    logo: 'qwik',
  },
  // Additional 2025 trends
  {
    id: 'astro-content',
    name: 'Astro Content',
    description: 'Astro with content collections and MDX',
    framework: 'next',
    features: ['typescript', 'tailwind'],
    documentation: 'https://astro.build/docs',
    category: '2025-trend',
    logo: 'astro',
  },
  {
    id: 'deno-fresh',
    name: 'Deno Fresh',
    description: 'Islands architecture with Deno and Fresh',
    framework: 'next',
    features: ['typescript', 'tailwind'],
    documentation: 'https://fresh.deno.dev/',
    category: '2025-trend',
    logo: 'deno',
  },
  {
    id: 'bun-react',
    name: 'Bun + React',
    description: 'Ultra-fast React development with Bun',
    framework: 'react',
    features: ['typescript', 'tailwind'],
    documentation: 'https://bun.sh/docs',
    category: '2025-trend',
    logo: 'bun',
  },
];
